social_app/routes.py
import json
from operator import and_
from flask import  make_response, render_template, send_from_directory, url_for, redirect, flash,Blueprint,request
from .forms import LoginForm,RegisterForm,PostForm
from social_app import app,db,mail,bcrypt,socketio,emit
from .models import Register,Post,Requests,Friends
from .token import generate_confirmation_token,confirm_token
from flask_mail import Message
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import or_
from base64 import b64encode
from pywebpush import webpush, WebPushException
import json

VAPID_SUBJECT = "mailto:your@email.com"
VAPID_PRIVATE = "ZiKbrfDYXh-Ra1xAJvIbLBPcUNo5OdThWz2g2UD-g8A"

auth = Blueprint(
	'auth',
	__name__,
	url_prefix='/auth'
)
home = Blueprint(
	'home',
	__name__,
	url_prefix='/home'
)
@auth.route('/index',methods=["GET","POST"])
@auth.route('/',methods=["GET","POST"])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('home.home_page'))
    form=LoginForm()
    if form.validate_on_submit():
        with app.app_context():
            register = Register.query.filter_by(email=form.email.data).first()
            if register is not None and bcrypt.check_password_hash(register.password,form.password.data):
                if register.is_active:
                    flash(f"Login Successfull {form.email.data}", "success")
                    login_user(register)
                    return redirect(url_for('home.home_page'))
                else:
                      flash(f"please verify email", "danger")
            else:
                flash(f"password erorr  or user name", "danger")
    return render_template('auth/index.html',title='index',form=form)	

@auth.route('/register',methods=["GET","POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home.home_page'))
    form=RegisterForm()
    if form.validate_on_submit():
        with app.app_context():
            pic=request.files['photo']
            if pic:
                hash_password = bcrypt.generate_password_hash(form.password.data).decode('utf8')
                register=Register(fName=form.fName.data,lName=form.lName.data,email=form.email.data,
                                password=hash_password,is_active=False,photo=pic.read())
                db.session.add(register)
                db.session.commit()
                token = generate_confirmation_token(form.email.data)
                confirm_url = url_for('auth.confirm_email', token=token, _external=True)
                html = render_template('auth/confirm_email.html', confirm_url=confirm_url)
                subject = "Please confirm your email"
                #send_email(form.email.data, subject, html)
                flash('A confirmation email has been sent via email.', 'success')
                return redirect(url_for('auth.index'))
    return render_template('auth/register.html',title='register',form=form)

@auth.route('/confirm/<token>',methods=["GET","POST"])
def confirm_email(token):
    if current_user.is_authenticated:
        return redirect(url_for('home.home_page'))
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    register=Register.query.filter_by(email=email).first()
    if register.is_active:
         flash('Account already confirmed. Please login.', 'success')
    else:
            register.is_active=True
            db.session.add(register)
            db.session.commit()
            flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('auth.index'))

def send_email(to, subject, template):
    msg = Message(
        subject,
        recipients=[to],
        html=template,
        sender='soonfu0@gmail.com'
    )
    mail.send(message=msg)

@home.route("/home_page",methods=["GET","POST"])
def home_page():
    if current_user.is_authenticated:
        posts=Post.query.all()
        post_filter=[]
        for p in posts:
            if p.privacy==1:
                f=Friends.query.filter_by(friends=p.register_id,register_id=current_user.id).first()
                if f:
                    post_filter.append(p)
                elif Friends.query.filter_by(friends=current_user.id,register_id=p.register_id).first():
                    post_filter.append(p)
                elif p.register_id==current_user.id:
                    post_filter.append(p)
            elif p.privacy==2:
                post_filter.append(p)
            else:
                if p.register_id==current_user.id:
                    post_filter.append(p)                   
                    
        users=[]
        images=[]
        images_posts=[]
        for p in post_filter:
            reg=Register.query.filter_by(id=p.register_id).first()
            users.append(reg)
            images.append( b64encode(reg.photo).decode("utf-8"))
            if p.image:
                images_posts.append(b64encode(p.image).decode("utf-8"))
            else:
                images_posts.append("")
        return render_template('home/index.html',
                            title='home',
                            posts=post_filter,
                            current_user_id=current_user.id,
                            users=users,
                            images_users=images,
                            images_posts=images_posts
                            )
    else:
        return redirect(url_for('auth.index'))

@home.route("/home_post_friends",methods=["GET"])
def home_post_friends():
    if current_user.is_authenticated:
        posts=Post.query.filter(and_(Post.privacy==1,Post.register_id!=current_user.id))
        post_filter=[]
        for p in posts:
            f=Friends.query.filter_by(friends=p.register_id,register_id=current_user.id).first()
            if f:
                post_filter.append(p)
            elif Friends.query.filter_by(friends=current_user.id,register_id=p.register_id).first():
                post_filter.append(p)
            
        users=[]
        images=[]
        images_posts=[]
        for p in post_filter:
            reg=Register.query.filter_by(id=p.register_id).first()
            users.append(reg)
            images.append( b64encode(reg.photo).decode("utf-8"))
            if p.image:
                images_posts.append(b64encode(p.image).decode("utf-8"))
            else:
                images_posts.append("")
        return render_template('home/index.html',
                            title='home',
                            posts=post_filter,
                            current_user_id=current_user.id,
                            users=users,
                            images_users=images,
                            images_posts=images_posts
                            )
    else:
        return redirect(url_for('auth.index'))
                           

@home.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('auth.index'))

@home.route("/add_post",methods=["GET","POST"])
def add_post():
    if current_user.is_authenticated:
        form=PostForm()
        if form.validate_on_submit():
            with app.app_context():
                pic=request.files['photo']
                if pic:
                    post=Post(image=pic.read(),des=form.des.data,privacy=form.privacy.data,register_id=current_user.id)
                    db.session.add(post)
                    db.session.commit()
                else:
                    post=Post(des=form.des.data,privacy=form.privacy.data,register_id=current_user.id)
                    db.session.add(post)
                    db.session.commit()
                return redirect(url_for('home.home_page'))
       # socketio.emit("reply", "emit successful")
        return render_template('post/add_post.html',title='add post',form=form)
    else:
        return redirect(url_for('auth.index'))
    
@socketio.event
def handle_init_event(data):
        emit("reply", "emit successful")


@home.route("/search",methods=['POST'])
def search():
    if current_user.is_authenticated:
        keyword = request.form.get('search')
        results=Register.query.filter(or_(Register.fName.like("%"+keyword+"%"),Register.lName.like("%"+keyword+"%"))).all()
        images=[]
        results_app=[]
        for r in results:
            req=Requests.query.filter_by(recive=r.id,send=current_user.id).first()
            if req:
                results.remove(r)
            elif Requests.query.filter_by(recive=current_user.id,send=r.id).first():
                results.remove(r)
            else:
                if r.id != current_user.id:
                    results_app.append(r)
                    images.append(b64encode(r.photo).decode("utf-8"))
            return render_template('home/friends_search.html',title='home',search=results_app,images=images)
    else:
        return redirect(url_for('auth.index'))

@home.route("/send",methods=['POST'])
def send():
     if current_user.is_authenticated:
        id = request.form.get('id')
        with app.app_context():
            req= Requests(send=current_user.id,recive=id)
            db.session.add(req)
            db.session.commit()
        flash('you send request to friend', 'success')
        socketio.emit("reply",
            id+"#"+
            current_user.__str__()+"#"+
            "send to you friend request"
        )
        return redirect(url_for('home.home_page'))
     else:
        return redirect(url_for('auth.index'))
     
@home.route("/send",methods=['GET'])
def requests():
    if current_user.is_authenticated:
        results=Requests.query.filter_by(recive=current_user.id,status=0)
        friends=[]
        images=[]
        for r in results:
            re=Register.query.filter_by(id=r.send).first()
            friends.append(re)
            images.append(b64encode(re.photo).decode("utf-8"))

social_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
    <title>
        {% block title %}
        {{ title }}
        {% endblock %}
    </title>
    {% block style %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          {% if title == 'index' %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('auth.index') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
          </li>
          {%else%}
          {% if title == 'register' %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.index') }}">Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
          </li>
          {% endif %}
          {% endif %}

          {% if title == 'home' %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('home.home_page') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('home.profile')}}">profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('home.requests') }}">friend requests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('home.my_friends') }}">friends</a>
          </li>
          {% endif %}

          {% if title == 'profile' %}
          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('home.home_page') }}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('home.profile')}}">profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('home.requests') }}">friend requests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('home.my_friends') }}">friends</a>
          </li>
          {% endif %}

          {% if title == 'friends' %}
          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('home.home_page') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('home.profile')}}">profile</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('home.requests') }}">friend requests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('home.my_friends') }}">friends</a>
          </li>
          {% endif %}
          {% if title == 'add post' %}
        <li class="nav-item ">
          <a class="nav-link" href="{{ url_for('home.home_page') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('home.profile')}}">profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('home.requests') }}">friend requests</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('home.my_friends') }}">friends</a>
        </li>
        {% endif %}
        </ul>
        {% if title == 'home' %}
        
        <ul class="navbar-nav ml-auto">
          <form method="POST" class="navbar-form navbar-left " action="{{ url_for('home.search') }}">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search" name="search">
              <div class="input-group-btn">
              </div>
            </div>
          </form>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              modes posts
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('home.home_post_friends')}}">friends only</a>
              <a class="dropdown-item" href="{{ url_for('home.home_page')}}">All posts</a>
            </div>
          </li>
          
          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('home.logout') }}">Logout</a>
          </li>
        </ul>
        {% endif %}
        
      </nav>
       <main>
        {% with messages = get_flashed_messages(with_categories=True) %}
          {% if messages %}
            {% for category,message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
       </main>
      <footer class="mainfooter bg-dark" role="contentinfo">  
        <div class="footer-middle">  
        <div class="container">  
          <div class="row">  
            <div class="col-md-3 col-sm-6">  
              <div class="footer-pad">  
                <h4> Footer Heading 1</h4>  
                <ul class="list-unstyled">  
                  <li> <a href="#"> </a> </li>  
                  <li> <a href="#">Payment Center</a></li>  
                  <li> <a href="#"> Contact Directory </a></li>  
                  <li> <a href="#">Forms</a></li>  
                  <li> <a href="#">News and Updates</a></li>  
                  <li> <a href="#">FAQs</a></li>  
                </ul>  
              </div>  
            </div>  
            <div class="col-md-3 col-sm-6">  
              <div class="footer-pad">  
                <h4> Footer Heading 2</h4>  
                <ul class="list-unstyled">  
                  <li><a href="#"> Blog </a> </li>  
                  <li><a href="#">Accessibility</a> </li>  
                  <li><a href="#">Disclaimer</a></li>  
                  <li><a href="#">Privacy Policy</a></li>  
                  <li><a href="#">FAQs</a></li>  
                  <li><a href="#">Webmaster</a></li>  
                </ul>  
              </div>  
            </div>  
            <div class="col-md-3 col-sm-6">  
              <div class="footer-pad">  
                <h4> Footer Heading 3 </h4>  
                <ul class="list-unstyled">  
                  <li> <a href="#"> Parks and Recreation </a> </li>  
                  <li> <a href="#"> Public Works </a> </li>  
                  <li> <a href="#">Police Department</a> </li>  
                  <li> <a href="#"> Fire </a> </li>  
                  <li> <a href="#"> Mayor and City Council </a> </li>  
                </ul>  
              </div>  
            </div>  
              <div class="col-md-3">  
                  <h4> Follow Us </h4>  
                  <ul class="social-network social-circle">  
                   <li> <a href="#" class="icoFacebook" title="Facebook"> <i class="fa fa-facebook"> </i> </a> </li>  
                   <li> <a href="#" class="icoLinkedin" title="Linkedin"> <i class="fa fa-linkedin"> </i> </a> </li>  
          <li> <a href="#"> <i class="fa fa-youtube" aria-hidden="true"> </i> </a> </li>  
                  </ul>               
          </div>  
          </div>  
          <div class="row">  
          <div class="col-md-12 copy">  
          <p class="text-center"> © Copyright 2021 - Company Name.  All rights reserved. </p>  
          </div>  
          </div>  
        </div>  
        </div>  
      </footer>  
      <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
  integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
  crossorigin="anonymous"></script>

      <script>
          var socket = io();
  socket.on('connect', function () {
    socket.emit('init', JSON.stringify({ username: '1' }));
  });
  socket.on("reply", (data) => {
    data_splits=data.split("#")
    if(data_splits[0]=='{{current_user.id}}')
    {
      regWorker('',data_splits[1],data_splits[2]);
    }

  })

         // (A) OBTAIN USER PERMISSION TO SHOW NOTIFICATION
  window.onload = () => {
    // (A1) ASK FOR PERMISSION
    if (Notification.permission === "default") {
      Notification.requestPermission().then(perm => {
        if (Notification.permission === "granted") {
          //regWorker('{{public_key}}').catch(err => console.error(err));
        } else {
          alert("Please allow notifications.");
        }
      });
    }

    // (A2) GRANTED
    else if (Notification.permission === "granted") {
     // regWorker('{{public_key}}').catch(err => console.error(err));
    }

    // (A3) DENIED
    else { alert("Please allow notifications."); }
  }
  // (B) REGISTER SERVICE WORKER
  async function regWorker(publicKey,title,body) {
    // (B1) YOUR PUBLIC KEY - CHANGE TO YOUR OWN!
    console.log(publicKey);
    // (B2) REGISTER SERVICE WORKER
    navigator.serviceWorker.register("http://127.0.0.1:5000/push.js");

    // (B3) SUBSCRIBE TO PUSH SERVER
    navigator.serviceWorker.ready
      .then(reg => {
        reg.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey:"BPc0T1X6JBbAg_JO-BMCjPoIUiwK6IV9GQkFl5UZznJSrzpH9A7c_i2oOTEiwIKteUBH4XHts1IFMvd9LAR3ZZg"
        }).then(
          // (B3-1) OK - TEST PUSH NOTIFICATION
          sub => {
            var data = new FormData();
            data.append("sub", JSON.stringify(sub));
            data.append("title", title);
            data.append("body", body)
            fetch("/push", { method: "POST", body: data })
              .then(res => res.text())
              .then(txt => console.log(txt))
              .catch(err => console.error(err));
          },

          // (B3-2) ERROR!
          err => console.error(err)
        );
      });
    }
      </script>
</body>
</html>