social_app/routes.py
import json
from operator import and_
from flask import  make_response, render_template, send_from_directory, url_for, redirect, flash,Blueprint,request
from .forms import LoginForm,RegisterForm,PostForm
from social_app import app,db,mail,bcrypt,socketio,emit
from .models import Register,Post,Requests,Friends
from .token import generate_confirmation_token,confirm_token
from flask_mail import Message
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import or_
from base64 import b64encode
from pywebpush import webpush, WebPushException
import json

VAPID_SUBJECT = "mailto:your@email.com"
VAPID_PRIVATE = "ZiKbrfDYXh-Ra1xAJvIbLBPcUNo5OdThWz2g2UD-g8A"

auth = Blueprint(
	'auth',
	__name__,
	url_prefix='/auth'
)
home = Blueprint(
	'home',
	__name__,
	url_prefix='/home'
)
@auth.route('/index',methods=["GET","POST"])
@auth.route('/',methods=["GET","POST"])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('home.home_page'))
    form=LoginForm()
    if form.validate_on_submit():
        with app.app_context():
            register = Register.query.filter_by(email=form.email.data).first()
            if register is not None and bcrypt.check_password_hash(register.password,form.password.data):
                if register.is_active:
                    flash(f"Login Successfull {form.email.data}", "success")
                    login_user(register)
                    return redirect(url_for('home.home_page'))
                else:
                      flash(f"please verify email", "danger")
            else:
                flash(f"password erorr  or user name", "danger")
    return render_template('auth/index.html',title='index',form=form)	

@auth.route('/register',methods=["GET","POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home.home_page'))
    form=RegisterForm()
    if form.validate_on_submit():
        with app.app_context():
            pic=request.files['photo']
            if pic:
                hash_password = bcrypt.generate_password_hash(form.password.data).decode('utf8')
                register=Register(fName=form.fName.data,lName=form.lName.data,email=form.email.data,
                                password=hash_password,is_active=False,photo=pic.read())
                db.session.add(register)
                db.session.commit()
                token = generate_confirmation_token(form.email.data)
                confirm_url = url_for('auth.confirm_email', token=token, _external=True)
                html = render_template('auth/confirm_email.html', confirm_url=confirm_url)
                subject = "Please confirm your email"
                #send_email(form.email.data, subject, html)
                flash('A confirmation email has been sent via email.', 'success')
                return redirect(url_for('auth.index'))
    return render_template('auth/register.html',title='register',form=form)

@auth.route('/confirm/<token>',methods=["GET","POST"])
def confirm_email(token):
    if current_user.is_authenticated:
        return redirect(url_for('home.home_page'))
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    register=Register.query.filter_by(email=email).first()
    if register.is_active:
         flash('Account already confirmed. Please login.', 'success')
    else:
            register.is_active=True
            db.session.add(register)
            db.session.commit()
            flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('auth.index'))

def send_email(to, subject, template):
    msg = Message(
        subject,
        recipients=[to],
        html=template,
        sender='soonfu0@gmail.com'
    )
    mail.send(message=msg)

@home.route("/home_page",methods=["GET","POST"])
def home_page():
    if current_user.is_authenticated:
        posts=Post.query.all()
        post_filter=[]
        for p in posts:
            if p.privacy==1:
                f=Friends.query.filter_by(friends=p.register_id,register_id=current_user.id).first()
                if f:
                    post_filter.append(p)
                elif Friends.query.filter_by(friends=current_user.id,register_id=p.register_id).first():
                    post_filter.append(p)
                elif p.register_id==current_user.id:
                    post_filter.append(p)
            elif p.privacy==2:
                post_filter.append(p)
            else:
                if p.register_id==current_user.id:
                    post_filter.append(p)                   
                    
        users=[]
        images=[]
        images_posts=[]
        for p in post_filter:
            reg=Register.query.filter_by(id=p.register_id).first()
            users.append(reg)
            images.append( b64encode(reg.photo).decode("utf-8"))
            if p.image:
                images_posts.append(b64encode(p.image).decode("utf-8"))
            else:
                images_posts.append("")
        return render_template('home/index.html',
                            title='home',
                            posts=post_filter,
                            current_user_id=current_user.id,
                            users=users,
                            images_users=images,
                            images_posts=images_posts
                            )
    else:
        return redirect(url_for('auth.index'))

@home.route("/home_post_friends",methods=["GET"])
def home_post_friends():
    if current_user.is_authenticated:
        posts=Post.query.filter(and_(Post.privacy==1,Post.register_id!=current_user.id))
        post_filter=[]
        for p in posts:
            f=Friends.query.filter_by(friends=p.register_id,register_id=current_user.id).first()
            if f:
                post_filter.append(p)
            elif Friends.query.filter_by(friends=current_user.id,register_id=p.register_id).first():
                post_filter.append(p)
            
        users=[]
        images=[]
        images_posts=[]
        for p in post_filter:
            reg=Register.query.filter_by(id=p.register_id).first()
            users.append(reg)
            images.append( b64encode(reg.photo).decode("utf-8"))
            if p.image:
                images_posts.append(b64encode(p.image).decode("utf-8"))
            else:
                images_posts.append("")
        return render_template('home/index.html',
                            title='home',
                            posts=post_filter,
                            current_user_id=current_user.id,
                            users=users,
                            images_users=images,
                            images_posts=images_posts
                            )
    else:
        return redirect(url_for('auth.index'))
                           

@home.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('auth.index'))

@home.route("/add_post",methods=["GET","POST"])
def add_post():
    if current_user.is_authenticated:
        form=PostForm()
        if form.validate_on_submit():
            with app.app_context():
                pic=request.files['photo']
                if pic:
                    post=Post(image=pic.read(),des=form.des.data,privacy=form.privacy.data,register_id=current_user.id)
                    db.session.add(post)
                    db.session.commit()
                else:
                    post=Post(des=form.des.data,privacy=form.privacy.data,register_id=current_user.id)
                    db.session.add(post)
                    db.session.commit()
                return redirect(url_for('home.home_page'))
       # socketio.emit("reply", "emit successful")
        return render_template('post/add_post.html',title='add post',form=form)
    else:
        return redirect(url_for('auth.index'))
    
@socketio.event
def handle_init_event(data):
        emit("reply", "emit successful")


@home.route("/search",methods=['POST'])
def search():
    if current_user.is_authenticated:
        keyword = request.form.get('search')
        results=Register.query.filter(or_(Register.fName.like("%"+keyword+"%"),Register.lName.like("%"+keyword+"%"))).all()
        images=[]
        results_app=[]
        for r in results:
            req=Requests.query.filter_by(recive=r.id,send=current_user.id).first()
            if req:
                results.remove(r)
            elif Requests.query.filter_by(recive=current_user.id,send=r.id).first():
                results.remove(r)
            else:
                if r.id != current_user.id:
                    results_app.append(r)
                    images.append(b64encode(r.photo).decode("utf-8"))
            return render_template('home/friends_search.html',title='home',search=results_app,images=images)
    else:
        return redirect(url_for('auth.index'))

@home.route("/send",methods=['POST'])
def send():
     if current_user.is_authenticated:
        id = request.form.get('id')
        with app.app_context():
            req= Requests(send=current_user.id,recive=id)
            db.session.add(req)
            db.session.commit()
        flash('you send request to friend', 'success')
        socketio.emit("reply",
            id+"#"+
            current_user.__str__()+"#"+
            "send to you friend request"
        )
        return redirect(url_for('home.home_page'))
     else:
        return redirect(url_for('auth.index'))
     
@home.route("/send",methods=['GET'])
def requests():
    if current_user.is_authenticated:
        results=Requests.query.filter_by(recive=current_user.id,status=0)
        friends=[]
        images=[]
        for r in results:
            re=Register.query.filter_by(id=r.send).first()
            friends.append(re)
            images.append(b64encode(re.photo).decode("utf-8"))

social_app/templates/home/friends_request.html
{% extends 'layout.html' %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/friends_search.css') }}">
{% endblock %}
{% block content %}
<div class="container">
    <h1>friends requests</h1>
    {% for f in friends %}
    <div>
    <a href="{{url_for('home.see_profile',id=f.id)}}"><img src="data:image/*;charset=utf-8;base64,{{ images[loop.index0] }}"   class="rounded-circle" alt="Cinque Terre"/></a>
    <span>{{f}}</span>
    <form style="display: inline;" class="mr-2" action="{{ url_for('home.reject') }}" method="post">
    <input type="hidden" value="{{f.id}}" name="id">
    <input type="submit" class="btn btn-danger float-right  ml-4"  value="reject request"/>
</form>
    <form style="display: inline;"  action="{{ url_for('home.accept') }}" method="post">
        <input type="hidden" value="{{f.id}}" name="id">
        <input type="submit" class="btn btn-primary float-right "  value="accept request"/>
    </form>
  
</div>
    {% endfor %}
</div>
<div style="height: 200px;"></div>
{% endblock %}

social_app/templates/home/friends_search.html
{% extends 'layout.html' %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/friends_search.css') }}">
{% endblock %}
{% block content %}
<div class="container">
    <h1>friends search</h1>
    {% for f in search%}
    <form action="{{ url_for('home.send') }}" method="post">
        <a href="{{url_for('home.see_profile',id=f.id)}}"><img src="data:image/*;charset=utf-8;base64,{{ images[loop.index0] }}"  class="rounded-circle" alt="Cinque Terre"/></a>
        <span>{{f}}</span>
        <input type="hidden" value="{{f.id}}" name="id">
        <input type="submit" class="btn btn-primary float-right"  value="send reques"/>
    </form>
    {% endfor %}
</div>
<div style="height: 200px;"></div>
{% endblock %}

social_app/templates/home/index.html
{% extends 'layout.html' %}
{% block style %}
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{ url_for('static', filename='css/post.css') }}">
{% endblock %}
{%block content%}

{% for p in posts %}
<section class="hero">
  <div class="container">
    <div class="row">

      <div class="col-lg-6 offset-lg-3">

        <div class="cardbox shadow-lg bg-white">

          <div class="cardbox-heading">
            <!-- START dropdown-->
            {% if current_user.id == p.register_id %}
            <div class="dropdown float-right">
              <button class="btn btn-flat btn-flat-icon" type="button" data-toggle="dropdown" aria-expanded="false">
                <em class="fa fa-ellipsis-h"></em>
              </button>

              <div class="dropdown-menu dropdown-scale dropdown-menu-right" role="menu"
                style="position: absolute; transform: translate3d(-136px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                <form action="{{url_for('home.update_post')}}" method="post">
                  <input type="hidden" name="id" value="{{p.id}}">
                  <input class="dropdown-item" value="update post" post type="submit" />
                </form>
                <form action="{{url_for('home.delete_post')}}" method="post">
                  <input type="hidden" name="id" value="{{p.id}}">
                  <input class="dropdown-item" value="delete post" post type="submit" />
                </form>

              </div>

            </div><!--/ dropdown -->
            {%endif%}
            <div class="media m-0">
              <div class="d-flex mr-3">
                <a href=""><img class="img-fluid rounded-circle"
                    src="data:image/*;charset=utf-8;base64,{{ images_users[loop.index0] }}" alt="User"></a>
              </div>
              <div class="media-body">
                <p class="m-0">{{users[loop.index0]}}</p>
                <!--<small><span><i class="icon ion-md-time"></i> 10 hours ago</span></small>-->
              </div>
            </div><!--/ media -->
          </div><!--/ cardbox-heading -->

          <div class="cardbox-item">
            <img class="img-fluid" style="width:100%"
              src="data:image/*;charset=utf-8;base64,{{ images_posts[loop.index0] }}" alt="">
          </div><!--/ cardbox-item -->

          <div>
            <p class="text-dark text-center mt-2 mb-2">{{p.des}}</p>
          </div><!--/ cardbox-like -->

        </div><!--/ cardbox -->
      </div><!--/ col-lg-6 -->
    </div><!--/ row -->
  </div><!--/ container -->
</section>

{%endfor%}
<div style="height: 300px;"></div>
<button type="button" class="btn btn-primary btn-lg" style="position:fixed; bottom:20px;right:20px; z-index:10;">
  <a href="{{ url_for('home.add_post') }}" class="visually-hidden text-light">Add Post</a>
</button>

{% endblock %}

social_app/templates/home/my_friends.html
{% extends 'layout.html' %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/friends_search.css') }}">
{% endblock %}
{% block content %}
<div class="container">
    <h1>my frends</h1>
    {% for f in friends%}
    <div class="container">
        <a href="{{url_for('home.see_profile',id=f.id)}}"><img src="data:image/*;charset=utf-8;base64,{{ images[loop.index0] }}"  class="rounded-circle mt-4" alt="Cinque Terre"/></a>
        <span>{{f}}</span>
    </div>
    {% endfor %}
</div>
<div style="height: 200px;"></div>
{% endblock %}

social_app/templates/home/profile.html
{% extends 'layout.html' %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">
{% endblock %}
{% block content %}

<div class="container rounded bg-white mt-5 mb-5">
    <div class="text-center">
        <a href="{{ url_for('home.profile')}}" class="btn btn-primary">edit profile</a>
        <a href="{{url_for('home.my_posts')}}" class="btn btn-primary">posts</a>
    </div>
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="data:image/*;charset=utf-8;base64,{{ images_user }}"><span class="font-weight-bold">{{current_user}}</span><span class="text-black-50">{{current_user.email}}</span><span> </span></div>
        </div>
        {% if posts %}
        <div class="col-md-9 border-right">
            {% for p in posts %}
<section class="hero mt-4">
  <div class="container">
    <div class="row">

      <div class="col-lg-6 offset-lg-3">

        <div class="cardbox shadow-lg bg-white">

          <div class="cardbox-heading">
            <!-- START dropdown-->
            {% if current_user.id == p.register_id %}
            <div class="dropdown float-right">
              <button class="btn btn-flat btn-flat-icon" type="button" data-toggle="dropdown" aria-expanded="false">
                <em class="fa fa-ellipsis-h"></em>
              </button>

              <div class="dropdown-menu dropdown-scale dropdown-menu-right" role="menu"
                style="position: absolute; transform: translate3d(-136px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                <form action="{{url_for('home.update_post')}}" method="post">
                  <input type="hidden" name="id" value="{{p.id}}">
                  <input class="dropdown-item" value="update post" post type="submit" />
                </form>
                <form action="{{url_for('home.delete_post')}}" method="post">
                  <input type="hidden" name="id" value="{{p.id}}">
                  <input class="dropdown-item" value="delete post" post type="submit" />
                </form>

              </div>

            </div><!--/ dropdown -->
            {%endif%}
            <div class="media m-0">
              <div class="d-flex mr-3">
                <a href=""><img class="img-fluid rounded-circle"
                    src="data:image/*;charset=utf-8;base64,{{ images_user }}"  style="width:50px;height: 50px;" alt="User"></a>
              </div>
              <div class="media-body">
                <p class="m-0">{{current_user}}</p>
                <!--<small><span><i class="icon ion-md-time"></i> 10 hours ago</span></small>-->
              </div>
            </div><!--/ media -->
          </div><!--/ cardbox-heading -->

          <div class="cardbox-item">
            <img class="img-fluid" style="width:100%"
              src="data:image/*;charset=utf-8;base64,{{ images_posts[loop.index0] }}" alt="">
          </div><!--/ cardbox-item -->

          <div>
            <p class="text-dark text-center mt-2 mb-2">{{p.des}}</p>
          </div><!--/ cardbox-like -->

        </div><!--/ cardbox -->
      </div><!--/ col-lg-6 -->
    </div><!--/ row -->
  </div><!--/ container -->
</section>

{%endfor%}
        </div>
        {%else%}
        <form action="{{url_for('home.update_profile')}}" method="POST" enctype="multipart/form-data"></form>
        <div class="col-md-9 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Settings</h4>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">First name</label><input type="text" class="form-control" placeholder="first name" value="{{current_user.fName}}" name="fName" required></div>
                    <div class="col-md-6"><label class="labels">Last name</label><input type="text" class="form-control" value="{{current_user.lName}}" placeholder="surname" name="lName" required></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Mobile Number</label><input type="text" class="form-control" placeholder="enter phone number" value="{{current_user.mobile_number}}" name="phone"></div>
                    <div class="col-md-12"><label class="labels">Address Line 1</label><input type="text" class="form-control" placeholder="enter address line 1" value="{{current_user.address1}}" name="address1"></div>
                    <div class="col-md-12"><label class="labels">Address Line 2</label><input type="text" class="form-control" placeholder="enter address line 2" value="{{current_user.address2}}" name="address1"></div>
                    <div class="col-md-12"><label class="labels">Postcode</label><input type="text" class="form-control" placeholder="enter Postcode" value="{{current_user.postcode}}" name="postcode"></div>
                    <div class="col-md-12"><label class="labels">State</label><input type="text" class="form-control" placeholder="enter State" value="{{current_user.state}}" name="state"></div>
                    <div class="col-md-12"><label class="labels">Country</label><input type="text" class="form-control" placeholder="enter country" value="{{current_user.Country}}" name="country"></div>
                     <div class="col-md-12"><label class="labels">Education</label><input type="text" class="form-control" placeholder="education" value="{{current_user.education}}" name="education"></div>
                     <div class="col-md-12"><label class="labels">Image</label><input type="file" class="form-control"  accept="image/png, image/gif, image/jpeg" name="photo" ></div>
                   
                </div>
                <div class="row mt-3">
                    <div class="col-md-6"><label class="labels">Password</label><input type="password" class="form-control" value="" name="password"></div>
                    <div class="col-md-6"><label class="labels">Confirm Password</label><input type="password" class="form-control" value="" name="confirm_password"></div>
                </div>
                <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="submit">Save Profile</button></div>
            </div>
        </div>
    </form>
    {% endif %}
    </div>
</div>
</div>
</div>

{% endblock %}

social_app/templates/home/see_profile.html
{% extends 'layout.html' %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">
{% endblock %}
{% block content %}

<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="data:image/*;charset=utf-8;base64,{{ images_user }}"><span class="font-weight-bold">{{user}}</span><span class="text-black-50">{{user.email}}</span><span> </span></div>
        </div>
        <div class="col-md-9 border-right">
            {% for p in posts %}
<section class="hero mt-4">
  <div class="container">
    <div class="row">

      <div class="col-lg-6 offset-lg-3">

        <div class="cardbox shadow-lg bg-white">

          <div class="cardbox-heading">
            <!-- START dropdown-->
            {% if current_user.id == p.register_id %}
            <div class="dropdown float-right">
              <button class="btn btn-flat btn-flat-icon" type="button" data-toggle="dropdown" aria-expanded="false">
                <em class="fa fa-ellipsis-h"></em>
              </button>

              <div class="dropdown-menu dropdown-scale dropdown-menu-right" role="menu"
                style="position: absolute; transform: translate3d(-136px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                <form action="{{url_for('home.update_post')}}" method="post">
                  <input type="hidden" name="id" value="{{p.id}}">
                  <input class="dropdown-item" value="update post" post type="submit" />
                </form>
                <form action="{{url_for('home.delete_post')}}" method="post">
                  <input type="hidden" name="id" value="{{p.id}}">
                  <input class="dropdown-item" value="delete post" post type="submit" />
                </form>

              </div>

            </div><!--/ dropdown -->
            {%endif%}
            <div class="media m-0">
              <div class="d-flex mr-3">
                <a href=""><img class="img-fluid rounded-circle"
                    src="data:image/*;charset=utf-8;base64,{{ images_user }}"  style="width:50px;height: 50px;" alt="User"></a>
              </div>
              <div class="media-body">
                <p class="m-0">{{current_user}}</p>
                <!--<small><span><i class="icon ion-md-time"></i> 10 hours ago</span></small>-->
              </div>
            </div><!--/ media -->
          </div><!--/ cardbox-heading -->

          <div class="cardbox-item">
            <img class="img-fluid" style="width:100%"
              src="data:image/*;charset=utf-8;base64,{{ images_posts[loop.index0] }}" alt="">
          </div><!--/ cardbox-item -->

          <div>
            <p class="text-dark text-center mt-2 mb-2">{{p.des}}</p>
          </div><!--/ cardbox-like -->

        </div><!--/ cardbox -->
      </div><!--/ col-lg-6 -->
    </div><!--/ row -->
  </div><!--/ container -->
</section>
{% endfor %}
        </div>
       
    </div>
</div>
</div>

{% endblock %}